const colors = [
  'primary',
  'primary-light',
  'primary-dark',
  'secondary',
  'secondary-light',
  'secondary-dark',
  'accent',
  'accent-light',
  'white',
  'neutral',
  'neutral-light',
  'neutral-dark',
  'neutral-80',
  'neutral-60',
  'neutral-40',
  'neutral-20',
  'success',
  'success-light',
  'danger',
  'danger-light',
  'warning',
  'warning-light',
];

export default colors;
