const icons = [
  'arrow-full-bottom',
  'arrow-full-top',
  'book-open',
  'briefcase',
  'calendar',
  'camera',
  'chat',
  'check-empty',
  'check',
  'cog',
  'credit-card',
  'document-text',
  'document-download',
  'exclamation-circle',
  'eye-off',
  'flag',
  'eye',
  'grid',
  'mail',
  'paper-airplane',
  'pencil',
  'pin-map',
  'question-mark-circle',
  'search',
  'social-facebook',
  'social-instagram',
  'social-twitter',
  'sun',
  'tribe',
  'user-group',
  'user',
];

export default icons;
