name: Mikado Reborn
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mikado_reborn
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build Package
        run: yarn workspace @livementor/mikado_reborn build
      - name: Build Doc
        run: yarn workspace doc build-storybook
