name: Mikado Reborn
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mikado_reborn
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          yarn install
          yarn build
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
